### ISSUE TITLE
Ingress port mapping

### ISSUE THREAD

**Issue by DaniTulp** [benthosdev/benthos-helm-chart#25]
When messing around with the ingress I think I found an issue with the way it's setup. At least it's not documented. When defining the ingress it uses the following [value](https://github.com/benthosdev/benthos-helm-chart/blob/main/templates/ingress.yaml#L3): 
```yaml
service:
   port: {number}
```
This doesn't seem to be in the `values.yaml`. I do see this `service.ports` field so maybe that should be used instead?

**Comment by difabion** [comment]
Admittedly, the ingress templating is not well-tested, and is mostly an artifact of the helm initialization logic for new projects.  I'll get you an answer on this sometime over the weekend.

**Comment by DaniTulp** [comment]
Yeah that makes sense. As the readme also states WIP + using something that's undocumented is probably not the _safest_ thing to do ;). 
Thought I'd at least mention it in case someone else hits it as well. For my use case just defining the port as shown above works perfectly fine.

**Comment by difabion** [comment]
Revisiting this this week, bear with me.

**Comment by DaniTulp** [comment]
No worries at all, due to the needs/opinions of the organisation I work for which (imo) don't directly align with what should be provided here (some quite specific options in terms of Azure for example). I've created our own helm chart (using this as reference of course 😉) that has those opinions baked in.
