### ISSUE TITLE
Support for adding labels to pod

### ISSUE THREAD

**Issue by DaniTulp** [benthosdev/benthos-helm-chart#27]
Would be nice if we could support adding additional labels to the container (similar to the `podAnnotations`), change would be added [here](https://github.com/benthosdev/benthos-helm-chart/blob/main/templates/deployment.yaml#L22) and adding an additional input value, maybe `podLabels`.
For us it would unlock us to use https://docs.datadoghq.com/getting_started/tagging/unified_service_tagging/?tab=kubernetes#partial-configuration. 

If this sounds useful I can look to add this.

**Comment by difabion** [comment]
Thanks for the contribution, merged!
