### ISSUE TITLE
Add support for `command` and `args`  fields that replaces the entrypoint command of the docker

### ISSUE THREAD

**Issue by bhataprameya** [benthosdev/benthos-helm-chart#34]
Add support for `command` and `args` fields that replaces the entrypoint command of the docker. This will be necessary if we have to manipulate some commands, or do some additional operations inside docker before the docker starts

**Comment by bhataprameya** [comment]
PR: https://github.com/benthosdev/benthos-helm-chart/pull/36

**Comment by difabion** [comment]
Thanks for the suggestion, and the PR; sorry for the slow response.  I will review this week.

**Comment by difabion** [comment]
Added in next release.
