### ISSUE TITLE
Having http.read_timeout configured in configmap causes Benthos startup failure

### ISSUE THREAD

**Issue by lovuikeng** [benthosdev/benthos-helm-chart#45]
Using the latest Helm chart version,  0.7.1, results in benthos container failed to start with error: `Config lint error" @service=benthos lint="/benthos.yaml(4,1) field read_timeout not recognised`   [https://github.com/benthosdev/benthos-helm-chart/blob/main/templates/configmap.yaml#L14](url) , the issue is not found on 0.6.0

**Comment by difabion** [comment]
I just posted 0.7.2 which removes this config option - I didn't realize this was removed from Benthos some time ago, sorry about that.

**Comment by lovuikeng** [comment]
no worries, appreciate the fix :-)
